### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by studgeek** [ku/CreateLink#13]
It would be handy if the extension allowed assigning keyboard shortcuts to formats as described here - https://developer.chrome.com/extensions/commands.

**Comment by malcook** [comment]
+1

**Comment by patkujawa-wf** [comment]
+1. [chitsaou/copy-as-markdown: Copying Link, Image and Tab(s) as Markdown Much Easier.](https://github.com/chitsaou/copy-as-markdown/) is another open source extension that does this:
![image](https://cloud.githubusercontent.com/assets/6391742/13153645/5e8e16d0-d632-11e5-9b5b-f85174b043b0.png)

I think the code they use is at https://github.com/chitsaou/copy-as-markdown/blob/master/src/command.js.

**Comment by patkujawa-wf** [comment]
@ku are you open to pull requests if I do add this feature? I don't want to have to load a local extension :)

**Comment by patkujawa-wf** [comment]
@ku would you take a look at my PR? I'd love to get this into the main extension and into the store.

**Comment by patkujawa-wf** [comment]
@ku please take a look, I want this in the store so everyone can benefit.
